# Generated by Django 3.2.9 on 2021-12-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationtaskgroup',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classificationtask',
            unique_together={('html_table', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='htmltable',
            unique_together={('xpath', 'source_document')},
        ),
    ]
