# Generated by Django 3.2.9 on 2021-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ADMIN', 'Admin')], default='NORMAL', max_length=64, verbose_name='Type'),
        ),
    ]
